### ISSUE TITLE
Use sklearn KMeans to divide into 5 categories

### ISSUE THREAD

**Issue by chrisrichardson** [ai4er-cdt/weather-fun#20]
Something like this:

`km = KMeans(n_clusters=5, random_state=0).fit(b)`

where `b` is the array of normalised data shape (n, 3) where n is the number of days and there are three components (rain, wind, sun).

**Comment by chrisrichardson** [comment]
Use matplotlib `projection=3d` to plot a 3D graph.

**Comment by anna-allen** [comment]
resolved in #24
