### ISSUE TITLE
Read in CSV file to a pandas DataFrame

### ISSUE THREAD

**Issue by chrisrichardson** [ai4er-cdt/weather-fun#7]
Once issue #5 is complete, use the `pandas` library to import the data as a `DataFrame`.

(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)

* Use the `pandas.read_csv` method to import the data
* Add headings to each column somehow

**Comment by anna-allen** [comment]
Resolved #11
